GET http://localhost:3005/programs

###GET user by id

GET  http://localhost:3005/progrmas/6522dcc0295223b3d126a509

### Create Contact
POST http://localhost:3005/programs/6522dcc0295223b3d126a509 HTTP/1.1
Content-type: aplication/json

{
    "TITLE": "example",
    "GENRE": "diferent",
    "SEASONS": 5,
    "CREATOR": "Vince Gilligan",
    "CAST": [
      "namwen",
      "anme",
      "name",
      "anme",
      "name"
    ],
    "RATING": 9.5
}

###PUT contact

PUT http://localhost:3005/programs/6522dd5d295223b3d126a50a HTTP/1.1
Content-type: application/json

{
     "TITLE": "example",
    "GENRE": "diferent",
    "SEASONS": 5,
    "CREATOR": "Vince Gilligan",
    "CAST": [
      "namwen",
      "anme",
      "name",
      "anme",
      "name"
    ],
    "RATING": 9.5

}

### DELETE contact

DELETE http://localhost:3005/programs/6522dcc0295223b3d126a509 HTTP/1.1